# Generated by Django 3.0.5 on 2020-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200603_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=120),
        ),
    ]
