# Generated by Django 3.0.5 on 2020-06-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200603_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='city',
            new_name='district',
        ),
    ]
