# Generated by Django 3.0.5 on 2020-06-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200603_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='district',
        ),
    ]
