# Generated by Django 3.0.5 on 2020-06-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200603_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billiing_profile',
            new_name='billing_profile',
        ),
    ]
