# Generated by Django 3.0.5 on 2020-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200607_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.CharField(default='ReadMore', max_length=120),
            preserve_default=False,
        ),
    ]
