# Generated by Django 3.0.5 on 2020-06-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product'},
        ),
    ]
